### PR TITLE
add gat/gat_multi operation

### PR DESCRIPTION
**Pull request by negachov**
Memcached gat operation is implemented in memcached 1.5.3 and above.
(https://github.com/memcached/memcached/wiki/ReleaseNotes153)

### CODE REVIEW

**Comment by negachov** [comment]
Please review.
@JRaspass

**Comment by JRaspass** [comment]
Sorry for the slow review, this change looks really good! Merged. I'll try and get a CPAN release out this week.

**Comment by negachov** [comment]
Thanks!

**Comment by JRaspass** [comment]
Shipped!

**Comment by negachov** [comment]
Thank you very much!

**Pull request merged**
